### ISSUE TITLE
Command-buffering synchronously-constructed promisey connections

### ISSUE THREAD

**Issue by stuartpb** [rethinkdb/rethinkdb#4315]
Basically, for the JS driver, I want to get a connection object immediately from r.connect() (or a similar function) that I can then pass to queries' `.run()`, and it will add the command to the connection promise's `.then` callback.

Something like this:

```
var conn = r.connection(cfg.rethinkdb);
conn.use('example');
r.insert({stuff:'foo',things:['bar','baz']}).run(conn);

// would work like:

r.connect(cfg.rethinkdb).then(conn => {
  conn.use('example');
  r.insert({stuff:'foo',things:['bar','baz']}).run(conn);
})
```

Right now, if I want this behavior, I have to use rethinkdbdash, which has problems (namely, I can't easily use it to run connection-agnostic queries constructed with a module like https://github.com/stuartpb/endex).

**Comment by marshall007** [comment]
This was brought up a while back in #2570. The main issue with having `.run()` take a promise was that you need to be able to call `conn.close()` at some point, but you don't have a resolved instance. This wouldn't be an issue if #4026 happens though, so this might be worth reconsidering.

> namely, I can't easily use it to run connection-agnostic queries

I think you can actually instantiate `rethinkdbdash` with `{pool: false}` and just pass a connection to `.run()` as usual.

**Comment by stuartpb** [comment]
> I think you can actually instantiate `rethinkdbdash` with `{pool: false}` and just pass a connection to `.run()` as usual.

That's using a `rethinkdb` connection for a query constructed with `retihkdbdash`. I'm talking about using the `rethinkdbdash` connection/pool for a query constructed with `rethinkdb`.

**Comment by stuartpb** [comment]
> This was brought up a while back in #2570. The main issue with having `.run()` take a promise was that you need to be able to call `conn.close()` at some point, but you don't have a resolved instance. This wouldn't be an issue if #4026 happens though, so this might be worth reconsidering.

Couldn't you handle `conn.close()` as normal if the connection has been established, and have it discard any pending queries (they will never resolve) if the connection was not established before being closed?

I'm not talking about returning an *actual promise*, I'm talking about returning a connection that *tracks* the promise.

**Comment by stuartpb** [comment]
*(Note that I just edited and expanded https://github.com/rethinkdb/rethinkdb/issues/4315#issuecomment-106997807 from its originally published form.)*

**Comment by deontologician** [comment]
I'm trying to see how this would work in practice. Take for example:

```js
var conn = r.connectionFuture(...)
conn.use('example')
var dataPromise = r.table('foo').run(conn)
dataPromise.then(function(data){
    return r.table('bar')./*some query dependent on data*/.run(conn)
}).then(function(){
   conn.close()
})

var secondPromise  = r.table('foo').get(x).run(conn)
secondPromise.then(function(secondData){
   ....run(conn)
})
```

So here we can assume `conn` is a wrapped connection promise. If it's not resolved, it chains itself onto a query. If it is resolved, it is used directly to run the query. It's not obvious which code will run first, or if everything will be run before close is called, or what.

It seems like we only get the benefits of this interface in the first query on the connection. It looks synchronous, but then in order to use the results we need to go back to the promise interface again.

@stuartpb is this how you're imagining it would work or is there something else you intended?

**Comment by stuartpb** [comment]
I'm not 100% sure I understood your question, but this isn't about making *queries* synchronous - only the ability to *initiate* them.

> If it's not resolved, it chains itself onto a query.

I'm not sure what this means - the way I would describe it, the connection more chains the query onto *it* than the other way around.

> It's not obvious which code will run first, or if everything will be run before close is called, or what.

Sure, but that's the same problem you *already* have in the case of two async calls (abstractly, at least - there might be some guarantees like #2711 about query ordering on the same connection that are, to my mind, a coincidence of implementation):

```
var conn = r.connect().then(function(conn){

conn.use('example')
var dataPromise = r.table('foo').run(conn)
dataPromise.then(function(data){
    return r.table('bar')./*some query dependent on data*/.run(conn)
}).then(function(){
   conn.close()
})

var secondPromise  = r.table('foo').get(x).run(conn)
secondPromise.then(function(secondData){
  /* can't dataPromise take longer and this gets called first? Or vice versa? */
   ....run(conn)
})

})
```

Queries in `rethinkdbdash` kind of work the way I describe - does https://github.com/rethinkdb/rethinkdb/issues/3771#issuecomment-107127070 illuminate this better?

**Comment by stuartpb** [comment]
Another thing that might help: my use case is in setting up apps by returning the handler that should be passed to `http.createServer`.

I want to make it so that, if a request comes in before the server connects to the RethinkDB host, running `r.get(req.session.username).run(conn).then(function(user){res.render('loggedin',{user: user})});` within the request handler will delay the response until the connection is established, rather than crashing the server with a `undefined is not a RethinkDB connection` error.

**Comment by deontologician** [comment]
>> It's not obvious which code will run first, or if everything will be run before close is called, or what.

> Sure, but that's the same problem you already have in the case of two async calls 

The issue I have with it is that it seems like the connection is resolved synchronously (since it isn't involving a callback or a promise). Since this isn't a standard kind of pattern, it means there's a bigger learning curve as to what operations are ok and what happens when you launch two queries in a row off of it. I

It also seems strange that we treat just the connection like this, and don't return futures from queries that were invoked with a future for a connection.

From your use case, it seems like a nice solution might be just storing the promise returned by `r.connect` somewhere, and then chaining your logic on it in your request handlers. Calling `.then` on an already resolved promise works as you'd expect.

**Comment by stuartpb** [comment]
> From your use case, it seems like a nice solution might be just storing the promise returned by `r.connect` somewhere, and then chaining your logic on it in your request handlers. Calling `.then` on an already resolved promise works as you'd expect.

That's... actually a potential solution, kind of, one I hadn't thought of. Doing `return conn` at the end of each `connPromise.then()`, and having each query have its own callback-local promise chain.

It's still not a super-elegant solution, and it's also kind of fragile (one mishandled `connPromise.then()` callback and the entire app blows up, with no tracebacks).

> It also seems strange that we treat just the connection like this, and don't return futures from queries that were invoked with a future for a connection.

It seems pretty straightforward to me - `conn` is a magic value that goes back into the driver, so it can resolve however it wants, but queries come directly to me, so they have to use the standard `Promise` (or Node callback) model.

> Since this isn't a standard kind of pattern

Sure it is - this is the model used by libraries like `rethinkdbdash` as well as (IIRC, outside the RethinkDB world) MongoDB libraries like `mongoskin`. It's just a general connection pool abstraction, where `run(conn)` means "run as soon as a connection's ready to handle this". (That's also why I would like to see this implemented as https://github.com/rethinkdb/rethinkdb/issues/3771#issuecomment-107127070.)

**Comment by stuartpb** [comment]
> It's still not a super-elegant solution, and it's also kind of fragile (one mishandled `connPromise.then()` callback and the entire app blows up at the next query with no tracebacks).

I guess that can be worked around somewhat by restricting access to the original connection promise, though:

```js
var conn;
function runNormally(query) {
  return query.run(conn);
}
var runQuery;
var connPromise = r.connect().then(function(connection) {
  conn = connection;
  runQuery = runNormally;
});
runQuery = function queueQueryRun(query) {
    return new Promise(function(resolve,reject) {
      connPromise.then(function(conn){
        query.run(conn).then(resolve).catch(reject);
        return conn;
      });
    });
  }
```
