### ISSUE TITLE
Cannot install RethinkDB from latest sources on OS X Yosemite

### ISSUE THREAD

**Issue by sreekaranugu** [rethinkdb/rethinkdb#5230]
I'm keep getting this error while trying to install on OS X Yosemite. I can't get rid of this, as there isn't much information related to it.

```
git clone URL
./configure --allow-fetch
make
```

The error is:

```
npm ERR! argv "/usr/local/Cellar/node/5.3.0/bin/node" "/usr/local/bin/npm" "--userconfig" "/Users/sreekar/github/rethinkdb/rethinkdb/mk/support/config/npm.conf" "--cache" "/Users/sreekar/github/rethinkdb/rethinkdb/external/npm_cache-SeFruCOS" "--no-registry" "install" "/Users/sreekar/github/rethinkdb/rethinkdb/external/admin-deps_2.0.3"
npm ERR! node v5.3.0
npm ERR! npm v3.3.12

npm ERR! registry URL is required
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR! https://github.com/npm/npm/issues
npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/Cellar/node/5.3.0/bin/node" "/usr/local/bin/npm" "--userconfig" "/Users/sreekar/github/rethinkdb/rethinkdb/mk/support/config/npm.conf" "--cache" "/Users/sreekar/github/rethinkdb/rethinkdb/external/npm_cache-SeFruCOS" "--no-registry" "install" "/Users/sreekar/github/rethinkdb/rethinkdb/external/admin-deps_2.0.3"
npm ERR! node v5.3.0
npm ERR! npm v3.3.12

npm ERR! registry URL is required
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR! https://github.com/npm/npm/issues

npm ERR! Please include the following file with any support request:
npm ERR! /Users/sreekar/github/rethinkdb/rethinkdb/build/external/admin-deps_2.0.3/npm-debug.log

Full error log: ./build/external/admin-deps_2.0.3_install.log
make[1]: *** [build/external/admin-deps_2.0.3/bin/gulp] Error 1
make: *** [make] Error 2
```

Thanks

**Comment by danielmewes** [comment]
@larkost Do you have any ideas about this one?

**Comment by danielmewes** [comment]
@sreekaranugu Could you try `./configure --allow-fetch --fetch npm --fetch node`?

**Comment by AtnNn** [comment]
@sreekaranugu That is an interesting bug. The RethinkDB build system has been using the `--no-registry` to npm, but your `npm` complains that "ERR! registry URL is required".

You should be able to work around that error by copying the `precompiled/` folder from the RethinkDB source distribution and re-running `./configure --allow-fetch`.

Or as @danielmewes suggests, running `./configure --fetch npm --allow-fetch` might also work.

This issue might be fixed by rewriting the npm pkg scripts to copy files and use `npm rebuild` instead of using `npm install`.

**Comment by sreekaranugu** [comment]
@danielmewes @AtnNn  Fortunately `./configure --allow-fetch --fetch npm --fetch node` worked. I have been trying to solve this for a day now. I previously installed node using brew. I think my brew installation of node has something wrong. I will close this issue if no one is facing it other than me.

**Comment by danielmewes** [comment]
> This issue might be fixed by rewriting the npm pkg scripts to copy files and use npm rebuild instead of using npm install.

@AtnNn Do you think we should do this regardless?

**Comment by AtnNn** [comment]
Yes. I believe it would simplify the script a lot.

**Comment by AtnNn** [comment]
I tried doing this but I give up. `npm` is inconsistent, incomplete, under-documented and too opinionated. The code is in [atnnn/5230](https://github.com/rethinkdb/rethinkdb/commit/430a82cbb414949b9bdd6b595b25211aa7c93a2d) if anyone else wants to try.

**Comment by AtnNn** [comment]
Someone else on IRC was asking about this error.

I got a little too frustrated when I last tried fixing this issue. It might be possible instead, in the `./configure` script, to check if `npm` supports `--no-registry` and to automatically fetch it if not. It's not a good long-term solution but it would help anyone running into this issue.

**Comment by larkost** [comment]
@AtnNn: that sounds like a good idea, but I would modify it slightly to have the `./configure` script bail out rather than semi-silently change it to a fetch. That way people would be aware of what we are doing.

**Comment by AtnNn** [comment]
Simply replacing `--no-registry` with `--registry http://disabled-registry` seems to work with the latest version of npm on windows.

**Comment by danielmewes** [comment]
I've just run into the same issue on Ubuntu 16.04.

I can use `--fetch npm` for now, but we should fix this. Maybe with a patch similar to the work-around @AtnNn found?
```
diff --git a/mk/support/pkg/npm-pkg.inc b/mk/support/pkg/npm-pkg.inc
index 179e772..3ce9014 100644
--- a/mk/support/pkg/npm-pkg.inc
+++ b/mk/support/pkg/npm-pkg.inc
@@ -49,7 +49,7 @@ pkg_install () {
     mkdir -p "$install_dir/node_modules"
     local pkg
     pkg=$(niceabspath "$src_dir")
-    in_dir "$install_dir" npm --no-registry install "$pkg"
+    in_dir "$install_dir" npm --registry http://no-npm-registry.rethinkdb.com install "$pkg"
 
     local bin_dir="$install_dir/node_modules/$full_npm_package/node_modules/.bin/"
     mkdir -p "$install_dir/bin"
```

**Comment by danielmewes** [comment]
Linking @mbroadst 's pull request here https://github.com/rethinkdb/rethinkdb/pull/5698 which has a fix for this.

**Comment by dalanmiller** [comment]
Just got this on Raspberry Pi 3 running Rasbian Jessie Lite and was Googling, found this issue, `--fetch npm` so far has worked for me.

**Comment by mbroadst** [comment]
`--fetch npm` definitely works, but its a bit annoying to have to build it yourself if you already have it locally.  IMHO rethink should support both configurations, and I think the PR allows for that (at very least the PR could be updated to check for certain versions of npm and omit the registry that way)

**Comment by srh** [comment]
Possibly still a problem, if so you'll have to resort to `--fetch npm`.
