### ISSUE TITLE
Memory leak?

### ISSUE THREAD

**Issue by danielmewes** [rethinkdb/rethinkdb#5865]
We're seeing an increasing number of reports of high memory consumption lately on servers that have been running for a few days.

The reports so far have been for RethinkDB 2.3.3 and 2.3.4.

Will run some tests to verify that things are still working as expected and we haven't introduced a memory leak.

**Comment by cjhowe** [comment]
Working on a reproducible test for this.

**Comment by Omeryl** [comment]
While I can't easily reproduce, I've noticed this happens very very often in the last few releases.

**Comment by cjhowe** [comment]
Here's some information about the load at which we're seeing this behavior.

```
{
  "id": [
    "cluster"
  ],
  "query_engine": {
    "client_connections": 17,
    "clients_active": 3,
    "queries_per_sec": 6.437247872,
    "read_docs_per_sec": 0,
    "written_docs_per_sec": 9307.005771857
  }
}
```

**Comment by alanhamlett** [comment]
And another example of `r.db('rethinkdb').table('stats').get(["cluster"])` on v2.3.3 single node cluster:

```
{
  "id": [
    "cluster"
  ] ,
  "query_engine": {
    "client_connections": 4 ,
    "clients_active": 1 ,
    "queries_per_sec": 57.77637731200001 ,
    "read_docs_per_sec": 0 ,
    "written_docs_per_sec": 28.884627143
  }
}
```

**Comment by Omeryl** [comment]
In my case, we're not seeing high load. Quite the opposite, it was only a few writes/200 reads an hour.

**Comment by Omeryl** [comment]
On the other hand, a much busier cluster has not experienced this leakage:

```json
{
   "id":[
      "cluster"
   ],
   "query_engine":{
      "client_connections":10,
      "clients_active":1,
      "queries_per_sec":123.00510939200001,
      "read_docs_per_sec":111.744325702,
      "written_docs_per_sec":23.566022814
   }
}
```

**Comment by danielmewes** [comment]
@Omeryl @alanhamlett @cjhowe on which distribution/OS are you running?

**Comment by cjhowe** [comment]
Ubuntu 14.04 for the cluster here, pulled RethinkDB from the official apt repo. Some of the clients have been Windows proxies.

**Comment by Omeryl** [comment]
CentOS 6 from your repos.

**Comment by alanhamlett** [comment]
Ubuntu 14.04

**Comment by erikdubbelboer** [comment]
Maybe it depends on what kind of objects are being stored. We store very complex objects. On of our simpler objects looks like: http://dubbelboer.com/simpleobject.txt Many of our bigger objects are over 64kb in size and contain some very big strings as well.

**Comment by alanhamlett** [comment]
We only store very small objects, so it's not limited to complex objects.

**Comment by danielmewes** [comment]
Quick update: So far we haven't been able to reproduce this locally. We're still investigating.

One odd thing is that in some cases the issue seems to have appeared with RethinkDB 2.3.2 (which would make some sense, since we switched the memory allocator library in that version among some other things). But for others 2.3.2 is working fine and 2.3.3 seems to be the first version with issues (which has extremely few changes from 2.3.2, none of which seem related).

**Comment by erikdubbelboer** [comment]
@dalanmiller If you want I can compile one instance with debugging on our production cluster, and log things if that might be interesting.

**Comment by alanhamlett** [comment]
The memory leak happens consistently for me... received some error emails about not being able to connect to rtdb and noticed it using swap again today:

<img width="1200" alt="screen shot 2016-06-29 at 7 51 17 am" src="https://cloud.githubusercontent.com/assets/522344/16457438/5dac9f56-3dd0-11e6-98ed-2ff589b49c59.png">

@danielcompton do you want ssh access to this server? It's only used for testing rethinkdb so I could anonymize the data but keep writing so you can see the memory leak happening. Not sure if that would help find the problematic code though.

**Comment by danielcompton** [comment]
> @danielcompton do you want ssh access to this server?

I assume you meant @danielmewes? :)

**Comment by danielmewes** [comment]
@alanhamlett SSH access might be useful to check a few things. Please contact me via email to daniel@rethinkdb.com so I can send you an SSH key.

When did you take that screenshot? Was that while the issue was happening or later? It looks like RethinkDB there is just using 10.5 GB of RAM, which is in the expected range for a server with 16 GB of total RAM. It's not clear to me from the screenshot what's using the swap memory in that moment.

**Comment by danielmewes** [comment]
@erikdubbelboer noticed that this issue only appeared at a time where the storage system (disk I/o) was saturated.

@cjhowe , @Omeryl , @alanhamlett do you think the same might be the case in your scenarios? Could RethinkDB be bound by either disk bandwidth or random seeks / IOPS limits? You can check `iostat -d 1 -m` (or similar) to find out about the current disk bandwidth and IOPS.

**Comment by iquizzle** [comment]
I have not noticed any memory leaks on our 20-node cluster (running 2.3.4). I keep running plots of memory usage on all of our nodes.

![image](https://cloud.githubusercontent.com/assets/2335826/17301027/3be0bed6-57d2-11e6-87c6-ce9cf6b69855.png)


{
"id": [
"cluster"
] ,
"query_engine": {
"client_connections": 2608 ,
"clients_active": 31 ,
"queries_per_sec": 4174.313804833 ,
"read_docs_per_sec": 4070.1740399229993 ,
"written_docs_per_sec": 223.3171217179999
}
}

However -- we are perpetually getting swap usage for all nodes, even when they each have ~8GB RAM free.

**Comment by danielmewes** [comment]
@iquizzle Thanks for adding your data.

The swapping is likely due to the value of the "swappiness" kernel parameter. This answer on Askubuntu has an excellent explanation of the parameter and how to change it: http://askubuntu.com/a/103916/209792

**Comment by analytik** [comment]
We're running 5x RethinkDB 2.3.4 nodes on Docker/Kubernetes, using the official 2.3.4~0jessie binary. Nodes have 64GB RAM, and `--cache-size=5120`. I've configured one of our services to connect to instance `rethinkdb3` - this service runs a financial report (more on that later).

The two graphs show the same period of over 4 days - the first graph shows memory usage of the 5 docker containers - 4 nodes have mostly constant and consistent memory usage, but the one running reports just bloats up.

When a horizontal line changes color, it means we manually killed a rethinkdb pod. When the big blue line dropped down from ~55GB to ~10GB, it got OOM'd and automatically restarted by Kubernetes.

![screenshot 2016-08-23 14 37 04](https://cloud.githubusercontent.com/assets/372365/17890708/52e489e4-6940-11e6-8c09-179af940cd05.png)

The next graph is network traffic - the lower blue lines is one of "normal" rethinkdb nodes, the orange one is `rethinkdb3`, which runs the report.

![screenshot 2016-08-23 14 44 53](https://cloud.githubusercontent.com/assets/372365/17890717/5793db5c-6940-11e6-80d6-0910a10e70e0.png)

Here's a close-up of the same thing. The spikes correspond to the report running - usually only one, sometimes two of them run at the same time. The time range selected for the report linearly affects the complexity.
![screenshot 2016-08-23 14 58 27](https://cloud.githubusercontent.com/assets/372365/17891041/2fb1d6fa-6942-11e6-8157-c43030d6895f.png)

All tables have 5 shards, 5 replicas. Judging by the network graph, hundreds of megabytes of data are all joined on `rethinkdb3`, and the report returns only a kilobyte or so of data. We're working on completely changing how the report will work, but hopefully it will be useful in your bug hunting.

I will send the query and sample data to @danielmewes by email, since it's verbose. Basically it's several tables joined and map-reduced.

**Comment by danielmewes** [comment]
@analytik Thanks for the sample data and query. We'll see if we can reproduce the problem with that. For the comparably small cache size that you're using (~5GB), the ~55GB memory consumption of the `rethinkdb` process is clearly way too high.

**Comment by bsharpe** [comment]
Just to add more data - we have 5 nodes w/ 256G of RAM.   
We have systematically lowered the cache by 5G on each node until it quits swapping during a normal day of usage.  We started all of them at 128G of cache (1/2 available RAM)
2 of the nodes have stopped swapping with the cache set to 60G
3 of the nodes continue to swap and their cache is set to 40G
we have ~40 tables -- a dozen of those have >10 million rows  -- 2 have > 100 million
write usage is pretty constant throughout the day at around 5k w/s with reads jumping from 0 to 100k/s

This has been ongoing with 2.3.4 -- 2.3.4 w/ modified GC - and now 2.3.5 which we upgraded to last night.

Ubuntu 14.04.1 - Rethink 2.3.5 from official apt source - 256G RAM / 24 dual core cpus

**Comment by danielmewes** [comment]
@bsharpe Do you have data available for how much of the RAM is actually used by the rethinkdb process when it starts going into swap? We've recently found that Linux in the default configuration often places parts of a RethinkDB process into swap, long before memory is actually getting exhausted. We have refined our swapping-detection as a reaction to this ( https://github.com/rethinkdb/rethinkdb/issues/6020 ), but the patch is only going to ship with RethinkDB 2.4.0 .
A way to avoid swapping in these circumstances is to change the `swappiness` parameter. See the "RethinkDB is running out of memory" section in https://rethinkdb.com/docs/troubleshooting/ .

**Comment by bsharpe** [comment]
@danielmewes 
rethink is the only thing running on these servers (besides DataDog for reporting)
vm.swappiness is set to 1

```
CPU       4.4%                   Load   48-core  Mem    32.4%  active:    159G   Swap   32.5%
user:     2.9%  nice:     0.0%   1 min:   8.44   total:  252G  inactive: 83.8G   total: 1.91G
system:   1.0%  iowait:   0.4%   5 min:   5.30   used:  81.6G  buffers:  4.36M   used:   635M
idle:    95.6%  irq:      0.0%   15 min:  3.51   free:   170G  cached:    170G   free:  1.29G

Network    Rx/s    Tx/s   Processes 559,  1 running, 558 sleeping,  0 other sorted automatically
bond0    7.26Mb  15.8Mb
docker0      0b      0b    VIRT   RES  CPU%  MEM%   PID USER        NI S    TIME+ IOR/s IOW/s NAME
dummy0       0b      0b    175G 73.2G 190.4  29.1 31140 rethinkdb    0 S 20:03.63     0     0 rethinkdb
```

**Comment by danielmewes** [comment]
@bsharpe Thanks for the additional data. It's interesting that that node is using swap, since the `rethinkdb` process only seems to be using 73.2 GB of RAM right now. Maybe it has peaked to a much larger size at some point in the past?

**Comment by bsharpe** [comment]
That's all we can figure.  
However, i've found that stopping the rethink process does not free up all the RAM, or the swap.  Once rethink has been stopped -- we can do `sudo swapoff -a && sudo swapon -a` frees up the swap instantly.   Doing that with rethink running makes rethink very slow to respond.
We get a much longer time without swap if we do a full reboot of the system before bringing rethink back up.

**Comment by danielmewes** [comment]
@bsharpe If there was memory pressure due to RethinkDB, it's not unlikely that the kernel would have put some other (inactive) processes into swap first. That could explain the remaining swap usage after stopping `rethinkdb`.

**Comment by bsharpe** [comment]
@danielmewes so. just stopped the rethink process on one of the servers with swap....  180G of RAM was still being "used" but no processes in `ps` or `top` or `htop` are shown as using ram.   We're perfectly happy to share a terminal session on one of these machines sometime with one of your engineers...

**Comment by danielmewes** [comment]
@bsharpe If memory is in use with the `rethinkdb` process gone, that suggests that there's something else going on on the system. I'm not sure if we can help with that.
Do you know how the "used" RAM is measured? Maybe the number includes the kernel's buffer cache, in which case the memory would be expected to remain in use until it is needed elsewhere.

**Comment by dollschasingmen** [comment]
just here to +1 this issue. we've noticed that a cluster that has been up and running eventually falls over from memory issues even when very little is happening on the cluster (this was just a POC server that is not used in production yet)

**Comment by beenotung** [comment]
I seem to meet the similar problem.
The server was running fine with 1G RAM and 2G swap for two weeks.
But recently (these two days), the DB failed due to out of memory issue.
The rethinkdb_data used only 40M.

I restart the database yesterday and it worked for a day.
Today it happens again, and it ran out of memory after 20 seconds...

Versions:
rethinkdb 2.3.5~0xenial (GCC 5.3.1)
horizon 2.0.0
Ubuntu SMP (4.4.0-1028-aws)

**Comment by beenotung** [comment]
Turn out my issue was not related to RethinkDB.
The increased memory usage was caused by having too many secondary indies on one of the tables.

**Comment by TheNewBob** [comment]
We're experiencing severe memory issues too. We're running a non-clustered rethinkDB 2.3.6 on Ubuntu 14.04.5 LTS (Trusty Tahr) with 4 GB of RAM. When rethinkdb starts, it usually eats somewhere around 40% of that, and quickly climbs to over 70% in a matter of hours.
Usually the demand goes down to some percentage in the upper 60ies or lower 70ies abruptly after a while, presumably due to a garbage collection, to start climbing again. We observed that with longer operation (weeks) this threshold steadily increases until it reaches up into the 90ies, and finally crashes practically every service on the system when it reaches somewhere between 91% and 95% (even cron stops working). The database itself becomes unresponsive at this point, but doesn't crash entirely. The memory stays allocated until the service or the system is restarted.
Due to this behavior, we began restarting rethinkdb during the night. This has provided reasonable (though not great) stability for a few months now.

But lately, things are deteriorating again. It can happen that the memory usage shoots into critical levels before any garbage collection is performed. A week and a half ago, we had two failures within hours of each other. It then ran stable again until yesterday, when it failed again in the evening. That was fixed before closing up shop, but it failed again today in the early morning, and then again just before midday. This is the reason for me posting today. The situation is starting to become unsustainable, and any help to get stability to the system would be greatly appreciated. I'm willing to provide any information you might find useful. Trouble is, I don't know what you need.

We have so far been unable to find a connection between memory increase and other measurable influences like e.g. load. In fact, the DB tends to fail at times of less activity (evening or night). Today was the first time it failed during high-traffic time. Here's the rethinkdb stats, in case they help:
```
"id": [
    "server" ,
    "b5e6cf40-f6fc-45c1-ac0c-7aa8ce60cbee"
] ,
    "query_engine": {
    "client_connections": 5 ,
    "clients_active": 1 ,
    "queries_per_sec": 5.113103764 ,
    "queries_total": 81194 ,
    "read_docs_per_sec": 459.90205303400006 ,
    "read_docs_total": 10599926 ,
    "written_docs_per_sec": 0 ,
    "written_docs_total": 4693
} ,
```
If RethinkDB keeps more detailed statistical data about its performance and access somewhere, please let me know. I have been unable to find anything along those lines.
We have logs of the rethinkDB memory and CPU usage in 1-minute intervals reaching back to early august, though, if that would be any kind of help. 
Anything you could suggest to stabilise the DB in the short term would be greatly appreciated.

**Comment by erikdubbelboer** [comment]
@TheNewBob How about disk IO? In our experience the memory problems only occur when the disks can't keep up with RethinkDB.

**Comment by TheNewBob** [comment]
Thanks for replying. The disk is an AWS EBS volume. Both read and write latency are below 6ms most of the time, and never above 10ms, so I think I'm on the save side there.

I have observed significant improvement of the memory situation after cleaning out a whole bunch of deprecated tables yesterday evening. That is, not only has the overall consumption gone down (which was expected), but the "runaway effect" has also decreased, with the consumption now showing a clear tendency to stick around a certain point instead of just growing out of control with occasional relieve.
It's a bit early to tell if the effect is gone in the long term, but for now it's looking encouraging.

Have you seen the question I amended to my last comment? Because that would explain the behavior I'm observing. I.e. if the memory for all table metadata is allocated when rethinkdb starts, the current behavior of less memory growth is unexpected. If that memory is allocated when a table is required for the first time during runtime, then I have simply misinterpreted that behavior as a memory leak.

**Comment by srh** [comment]
The 8 MB overhead allocated at load.  It's because some data structures involved are just wasteful in terms of up-front memory usage.  But if you improve things after clearing about a bunch of old, unused tables, it suggests there's a more pernicious problem.  It might be that the algorithm allocating memory resources between tables isn't very good.

**Comment by jvmartins** [comment]
@TheNewBob we've been having a similar problem as the one you described. We see the memory going up about 30% per day; until it gets to ~95% and we are forced to restart.

The only real difference is we have just 3 tables with a lot of data on them instead of old deprecated tables. We have been improving our queries and trying to perform several benchmarks on it, but we still have this problem, so we are wondering: Have you taken any other measures against it?

**Comment by srh** [comment]
It is possible that a fix for some of these memory leaks will be available shortly (that is, if you're willing to run an unofficial release).  I don't know whether I've fixed any observable leak in v2.3.6, or v2.3.5 or v2.3.4.  But it does fix a memory leak observed by a user of v2.3.6-srh-extra: https://github.com/srh/rethinkdb/releases/tag/v2.3.6-srh-extra  (That link is not to a *fixed* version.  One will be out soon.)

**Comment by iantocristian** [comment]
@srh the fix you mentioned in the post above, is it available on any release or branch?

**Comment by srh** [comment]
@iantocristian It turns out it wasn't a fix for the memory leak.  I have a branch with a rocksdb-based storage backend which is not production ready yet (arguably it's okay if you run a single node) and when I'm not overloaded with other stuff, I will be able to work on it.

**Comment by Kodehawa** [comment]
I'm interested as of why [the stability report of rethinkdb](https://rethinkdb.com/stability/) says that there's no known memory leaks, while this issue is still not addressed. 
No offense really, I've been using rethinkdb for the past 4 years and so far it has worked fine, but isn't it an issue that the stability report there says there's no known memory leaks :thinking:

Thanks you! 
I hope this can get fixed soon enough ;;

**Comment by v3ss0n** [comment]
that stability report is ages ago.  I am not sure where current devs are working now. 
@srh  @gabor-boros  where is official communication channel for Rethinkdb now?

**Comment by Kodehawa** [comment]
High priority report not addressed in 4 years is a scary thought.

**Comment by analytik** [comment]
It's reported on a different version. If it doesn't happen to you, then don't sweat it. Monitor your memory usage, that's about it.

**Comment by Kodehawa** [comment]
A friend gets a leak very similar to what has been reported on the latest version. But yeah, I just get overly worried :)

**Comment by analytik** [comment]
@Kodehawa - Oh, I didn't say there's no leak. I'm just saying, there isn't a sponsored development happening on RethinkDB, everything is done by volunteers, and databases are complex projects. As explained elsewhere, the better solution is to move RethinkDB internals to RocksDB, instead of the custom storage, which is probably the source of the memory leak.

My point was, monitoring comes first. If the bug happens to you, then you'll know it. There's a good chance it won't - which is what I meant. If you cannot take the risk, don't use RethinkDB. If you can take the risk, just put an alert into Grafana or whatever you use.

As you could see, I myself have reported this bug happening to us, and the best explanation I found, it happens when you join several tables, and use r.with() statements. I could be misremembering, I could be wrong. Monitor memory usage. Monitor app deploys. Correlate deploys with potential memory leak. I'd love to see this fixed, of course I would, but I'm saying, do not expect this to be fixed by any specific deadline. C++ developers with spare time are a scarce resource.

**Comment by Kodehawa** [comment]
Ah yeah. Fair. I'm just a little paranoid, but I have been using rethink for almost 5 years without too many issues (besides backups taking 3 hours, but they're small at least)

Did you end up fixing it on your side? More so out of curiosity :)

**Comment by analytik** [comment]
I'm not sure how far is the RocksDB implementation, but yes, that was the attempt, pre-2.4.0.

Basically, RethinkDB has a huge write amplification, so deleting 3000 documents when you have 50M of them in a table creates 100MB/s writes, and deleting the same 3000 documents when you have 1M table takes 20MB/s writes (and completes much faster).

I love the premise of RethinkDB, but without being able to log slow queries (without monitoring the activity table, which also can cause a few MB/s network traffic) and having a sensible disaster recovery restore (e.g. our DR restore would have taken 28 hours), this became unsustainable. 

It's super stable if you have <30GB of data maybe. We've had maybe 1.5TB and it was completely unreliable at that size, and we've had many hours of downtime because RethinkDB crashed and took 6 minutes to rebalance tables, sometimes freezing for hours, misreporting shards as underreplicated, unavailable, etc.

Anyway sorry to others for getting offtopic. Yes, we managed to avoid the memory leak by changing the way the queries were done, but it was years ago so sorry if I can't be any more helpful.

**Comment by srh** [comment]
It's interesting that you had it on joins.

Maybe it was caused by the table scans themselves, in particular.

The RocksDB branch generally works, but only well if you don't run a multi-node cluster, and you'd be the beta tester.  I would only use it if you for some reason had to.

Regarding the stability report page, I think it could use a date stamp and some updates on it.  You can make a PR at https://github.com/rethinkdb/docs or https://github.com/rethinkdb/www to update the website.  (Maybe that'd be more convincing if the PR's from Sep 12 were merged; somebody (cough, me) should get on that.)

My delay in replying since Oct 14 is because I've been quite busy.  Merely 45-hours-per-week busy, but I'm relatively low-energy.

**Comment by analytik** [comment]
It's good to see you alive & kicking - don't beat yourself up, it's nice that you show up.

Actually maybe I misspoke about the memory leak. Joins were there, but we had plenty of queries with joins that worked well enough. The particular query was a large analytical monster with 20-ish nested levels of `r.do()` or `r.with()`. I'm just slowly getting war flashbacks.
